"use strict";
let estaVivo = true;
console.log(estaVivo);
let edad = 30;
let salary = 2000.123;
console.log(edad, salary);
let mensaje = 'Este es mi mensaje';
console.log(mensaje);
let cantidad = 123;
cantidad = 123456;
console.log(cantidad);
cantidad = true;
console.log(cantidad);
cantidad = "mucho";
console.log(cantidad);
let arreglo = [1, 2, 3, 4, 5, 6];
arreglo.push(80);
let arreglo_cad = ['uno', 'dos', 'tres'];
arreglo_cad.push('once');
console.log(arreglo);
let movies = ["Logan", 8];
movies[0] = "8";
movies[1] = 8;
console.log(movies);
var Volumen;
(function (Volumen) {
    Volumen[Volumen["min"] = 1] = "min";
    Volumen[Volumen["medio"] = 5] = "medio";
    Volumen[Volumen["alto"] = 10] = "alto";
})(Volumen || (Volumen = {}));
let audio = Volumen.medio;
console.log(Volumen);
console.log(audio);
console.log(Volumen[10]);
function help() {
    console.log(`S.O.S`);
}
help();
let cualquier = "lo que sea";
let largoDeCadena = cualquier.length;
console.log(largoDeCadena);
